---
on:
  push:
    branches:
      - master
name: Terragrunt GitHub Actions
jobs:
  terragrunt:
    name: 'Terragrunt - Prod'
    runs-on: [self-hosted, terragrunt]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Execute terragrant apply-all'
        shell: bash
        working-directory: ./devops/prod
        run: |
          terragrunt init
          terragrunt apply-all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
