---
on:
  push:
    branches:
      - master
name: Terragrunt GitHub Actions
jobs:
  terragrunt:
    name: 'Terragrunt - Prod'
    runs-on: [self-hosted, terragrunt]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Echo something'
        run: echo terragrunt -v
