---
on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: ./devops
name: Packer and Terragrunt Actions
jobs:
  deploy:
    name: 'Packer and Terragrunt - Prod'
    runs-on: [self-hosted, terragrunt]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Packer build'
        shell: bash
        run: |
          packer build \
          -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "region=us-east-1" \
          -var "build_version=alpha-0.09" \
          packer.json
      - name: 'Execute terragrant apply-all'
        shell: bash
        working-directory: ./devops/prod
        run: |
          terragrunt init
          terragrunt apply-all --terragrunt-non-interactive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
