# This workflow fires whenever a PR is created, prior to approval.
# The PR should not be approved if this workflow does not pass.
on: pull_request
name: Tests and code
jobs:
  phpcs:
    name: PHPCS automated code review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@v2.0.2
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        SKIP_FOLDERS: "tests,.github,devops"
      with:
        args: "PEAR"
