# This workflow fires whenever a PR is created, prior to approval.
# The PR should not be approved if this workflow does not pass.
on: pull_request
name: Tests and code
jobs:
  phplint:
    name: PHP Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: michaelw90/PHP-Lint@master
    - name: Slack nofity
      if: failure()
      uses: thollander/actions-comment-pull-request@master
      with:
        message: 'Example of message !'
        GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
